#!/usr/bin/env python
# -*- coding: utf-8 -*-
#Author: Tim Henderson
#Email: tim.tadh@hackthology.com
#For licensing see the LICENSE file in the top level directory.

import os, sys
from getopt import getopt, GetoptError
import markdown

usage_message = \
'''usage: stat.py [Options] [FILE]+'''

extended_message = \
'''
Explanation

    Generates statistics on parse trees. "[FILE]+" is a list of files containing
    serialized parse trees. The format for the parse tree is a pre-order
    enumeration.

      grammar
       
        nodes := nodes node
        nodes := node
        node := NUM COLON STRING NEWLINE
        
        COLON = r':'
        NUM = r'[0-9]+'
        STRING = r'.+$'
        NEWLINE = "\\n"

        NB: Whitespace is signficant, but STRING matches whitespace (except for
            newline).
      
      eg.
        
        2:root
        2:left side
        0:x
        1:y
        0:z
        3:right side
        0:a
        0:b
        0:c

      corresponds to
                              root                                        
                              /  \                                        
                             /    \                                       
                    left side      right side                         
                    /    \         /    |    \                               
                   x      y       a     b     c                           
                          |                                               
                          z                                               
                                                                                  
Options

    -h, help                            print this message   
    -v, version                         print the version
    -g, grammar=<file>                  supply a known grammar to annotate
    -o, outdir=<directory>              supply a path to a non-existant
                                          directory
                                          [default: ./gramstats]
    -i, imgs=<bool>                     generate images
                                          [default: true]
    -t, tables=<bool>                   generate statistic tables (as csv files)
                                          [default: true]
    -a, artifacts                       list what artifacts `stat.py` can
                                          generate
    -A, artifact=<artspec>              generate a specific artifact only.
                                          Multiple '-A' flags allowed.
                                          [overrides -o,-i, and -t]
    -T, usetables=<directory>           look for pre-existing statistic tables
                                          in this directory. With this option
                                          no other files are required, however
                                          if more examples are given the tables
                                          are updated. The new tables will only
                                          overwrite the old tables if
                                          "-o <dirname>" == "-T <dirname>"

Specs

    <file>                              the path to a file
    <directory>                         the path to a directory.
    <bool>                              either "true" or "false"
    <artspec>                           <artifact>:<file>
    <artifact>                          an artifact in the list generated by
                                          --artifacts

'''

error_codes = {
    'usage':1,
    'file_not_found':2,
    'option':3,
    'args':4,
}

def log(msg):
    print msg

def usage(code=None):
    '''Prints the usage and exits with an error code specified by code. If code
    is not given it exits with error_codes['usage']'''
    log(usage_message)
    if code is None:
        log(extended_message)
        code = error_codes['usage']
    sys.exit(code)

def main(args):

    try:
        opts, args = getopt(args, 'h', ['help'])
    except GetoptError, err:
        log(err)
        usage(error_codes['option'])
      
    for opt, arg in opts:
        if opt in ('-h', '--help'):
            usage()
    

if __name__ == '__main__':
    main(sys.argv[1:])

